name: Build

on: [push, pull_request]

jobs:
  build-forge-monitor:
    name: Build Forge Monitor
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt-get -y install flex bison re2c

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Clone PHP
        run: git clone --single-branch --branch PHP-8.0.19 https://github.com/php/php-src.git

      - name: Clone PHPMicro
        run: git clone https://github.com/dixyes/phpmicro.git php-src/sapi/micro

      - name: Move into php-src directory
        run: cd php-src

      - name: Apply PHPMicro Patch
        run: patch -p1 < sapi/micro/patches/cli_checks.patch

      - name: Build
        run: ./buildconf --force

      - name: Configure
        run: ./configure --disable-phpdbg --disable-cgi --disable-all --enable-micro --enable-phar --with-ffi --enable-pdo

      - name: Make Micro
        run: make micro

      - name: Build Forge Monitor
        run: ./application app:build --build-version=unreleased

      - name: Compile Forge Monitor
        run: cat php-src/sapi/micro/micro.sfx forge-monitor/builds/application > /tmp/monitor
