name: Build

on: [push, pull_request]

jobs:
  prepare:
    name: Compile PHP with Micro
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt-get -y install flex bison re2c libonig-dev libsqlite3-dev

      - name: Clone PHP
        run: git clone --single-branch --branch PHP-8.0.19 https://github.com/php/php-src.git

      - name: Clone PHPMicro
        run: git clone https://github.com/dixyes/phpmicro.git php-src/sapi/micro

      - name: Apply PHPMicro Patch
        run: |
          cd php-src
          patch -p1 < php-src/sapi/micro/patches/cli_checks.patch

      - name: Build
        run: |
          cd php-src
          ./buildconf --force

      - name: Configure
        run: |
          cd php-src
          ./configure --disable-phpdbg --disable-cgi --disable-cli --disable-all --enable-micro --enable-phar --enable-pdo --with-zlib --with-iconv --enable-filter --with-pdo-sqlite --with-sqlite3

      - name: Make Micro
        run: |
          cd php-src
          make micro

      - uses: actions/upload-artifact@v2
        with:
          name: micro
          path: php-src/sapi/micro/micro.sfx

  build-forge-monitor:
    needs: prepare

    name: Build Forge Monitor
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Obtain Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: json, dom, curl, libxml, mbstring, zip
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Build Forge Monitor
        run: ./application app:build --build-version=unreleased

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: micro

      - name: Compile Forge Monitor
        run: cat ./micro.sfx ./builds/application > monitor

      - name: Upload the binary to release
        uses: actions/upload-artifact@v3
        with:
          name: monitor
          path: monitor
