name: Build

on: [push, pull_request]

jobs:
  prepare:
    name: Compile PHP with Micro
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt-get -y install flex bison re2c libonig-dev libsqlite3-dev

      - name: Clone PHP
        run: git clone --single-branch --branch PHP-8.0.19 https://github.com/php/php-src.git

      - name: Clone PHPMicro
        run: git clone https://github.com/dixyes/phpmicro.git php-src/sapi/micro

      - name: Apply PHPMicro Patch
        run: (cd php-src && patch -p1) < php-src/sapi/micro/patches/cli_checks.patch

      - name: Build
        run: ./php-src/buildconf --force

      - name: Configure
        run: ./php-src/configure --disable-phpdbg --disable-cgi --disable-cli --disable-all --enable-micro --enable-phar --enable-pdo --with-zlib --with-iconv --enable-filter --with-pdo-sqlite --with-sqlite3

      - name: Make Micro
        run: make micro

  build-forge-monitor:
    needs: prepare

    name: Build Forge Monitor
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build Forge Monitor
        run: ./application app:build --build-version=unreleased

      - name: Compile Forge Monitor
        run: cat php-src/sapi/micro/micro.sfx forge-monitor/builds/application > monitor
